### PR TITLE
Added product import via csv file

### PR DESCRIPTION
**Pull request by bojan93**
Hello, I've added import of products via csv file. If you have any comment regarding changes, please let me know.

### CODE REVIEW

**Comment by patroklossam** [comment]
Hi!

thanks for the contribution! I checked the code and it seems fine, except when the Product table is empty.. Then you get a NullPointerException when searching for the highest Id. Can you check it and in case there is no Id returned assign manually id 0 as the starting id?

I keep the PR open so that I can see the next commit and when you say it is ready I will check again and merge 

Cheers!

**Comment by bojan93** [comment]
I've missed that :D I've added fix.
Cheers!

**Comment by patroklossam** [comment]
Hi and thanks for the fix! One more request though... The issue description says to add a product only if not exists. I will merge your pull request, although I kindly ask you to also implement this feature (check which products from the file already exist and add only the rest of them) and create a new PR when you have it ready! 

This PR is valid! Thank you for the implementation

**Comment by bojan93** [comment]
Could you just tell me what makes one product unique?

**Comment by patroklossam** [comment]
Hi! sorry for the missing information! In my opinion brand and type make a product unique. I think a comparator in those 2 fields would easily solve the issue!

Thanks again! I already merged your previous commits so you can base your new branch on master again!

**Comment by bojan93** [comment]
Ok, thank you for answering! I'll start working as soon as I get some time. Cheers!

**Pull request merged**
