### PR TITLE
Unit Test for Entity classes

### PR DESCRIPTION
**Pull request by NyorJa**
Add Powermock

### CODE REVIEW

**Comment by patroklossam** [comment]
Hey ho, thanks for your contriution. I saw that for powermock it is using junit4.. is it possible to go for junit5???

**Comment by NyorJa** [comment]
yeah ill try again..i forgot to add d junit5 dependencies..gonna make a PR
again

**Comment by NyorJa** [comment]
i did check..it doesnt support junit5

**Comment by patroklossam** [comment]
Ok then! Unfortunately it is stated in the README that the project uses Junit5. Please just delete the HibernateTest if there is no alternative and commit the deletion! (remove the powermock dependency as no longer needed) and push the changes! I will merge the PR afterwards! Thanks for all the rest of the tests!

**Comment by patroklossam** [comment]
thanks again!

**Pull request merged**
